### ISSUE TITLE
[YML] - Which's the correct configuration in YML for a behat service

### ISSUE THREAD

**Issue by nietzscheson** [FriendsOfBehat/ServiceContainerExtension#11]
I have a service and some parameters for inject:

```yml
services:
    app.behat.page:
        class: AppBundle\Behat\Page\Page
        arguments: ['@mink.default_session', '*__behat__.mink.parameters']
        abstract: true
        public: false
```

When I run the bin/behat command, throw me this:

  The service "XXX" has a dependency on a non-existent service "mink.default_session".

**Comment by nietzscheson** [comment]
Found. I've does defined the min.default_session

```yml
services:
    mink.defaukt_session:
        class: Behat\Mink\Session
        public: false
        lazy: true
        factory: '@__behat__.mink:getSession'
```

I found. I've define the mink.default_session service. All is working...
