### ISSUE TITLE
Use MinkContext

### ISSUE THREAD

**Issue by arnolanglade** [FriendsOfBehat/ServiceContainerExtension#14]
I try to load context define as a service and simple context like `MinkContext` 
```
    suites:
        employee:
            contexts:
                - 'Behat\MinkExtension\Context\MinkContext'
            contexts_services:
                - al.employee.context
```
It seems that `MinkContext is not used because I have undefined steps like **I press 'something'**. What happen? did I do something wrong?

Thank you.
